### ISSUE TITLE
Recommended Labels - Name and Instance

### ISSUE THREAD

**Issue by Nalum** [stefanprodan/timoni#299]
Should the Timoni schema be updated so that the name provided to `timoni build` is set in the label `app.kubernetes.io/instance` and then the label `app.kubernetes.io/name` is set in the config as part of the metadata setup?

https://github.com/stefanprodan/timoni/blob/f44c6a8f11d915998616ae0394e73b760bd70439/schemas/timoni.sh/core/v1alpha1/metadata.cue#L44-L49

```cue
	#App: string & strings.MaxRunes(63)

	// Standard Kubernetes labels: app name, instance name, version and managed-by.
	labels: {
		"\(#StdLabelName)":      #App
		"\(#StdLabelInstance)":  name
		"\(#StdLabelVersion)":   #Version
		"\(#StdLabelManagedBy)": "timoni"
	}
```

```cue
	metadata: timoniv1.#Metadata & {#Version: moduleVersion, #App: "cert-manager"}
```

**Comment by Nalum** [comment]
Or should it be like this?

```cue
	#App: string & strings.MaxRunes(63)

	// Standard Kubernetes labels: app name, instance name, version and managed-by.
	labels: {
		"\(#StdLabelPartOf)":    #App
		"\(#StdLabelInstance)":  name
		"\(#StdLabelVersion)":   #Version
		"\(#StdLabelManagedBy)": "timoni"
	}
```

And then in each object the module maintainer would set:
- `metadata: labels: "\(timoniv1.#StdLabelName)": "controller"`
- `metadata: labels: "\(timoniv1.#StdLabelName)": "webhook"`
- `metadata: labels: "\(timoniv1.#StdLabelName)": "controller-config"`
- `metadata: labels: "\(timoniv1.#StdLabelName)": "webhook-config"`
- etc

**Comment by stefanprodan** [comment]
The instance name and namespace are set automatically by Timoni's server-side apply engine to track ownership, every object has these labels in cluster:
```yaml
instance.timoni.sh/name: <NAME>
instance.timoni.sh/namespace: <NAMESPACE>
```

Given this, I didn't want to add the Kubernetes instance label as it would be confusing. 

I suggest you add the `app.kubernetes.io/part-of` label to your modules, this can be done in the `#Config` with:

```cue
#Config: {
	metadata: labels: (timoniv1.#StdLabelPartOf): "cert-manager"
}
```

**Comment by ametad** [comment]
Hello @stefanprodan 

This choice about not using the `app.kubernetes.io/instance` label is somewhat confusing to me, because of the explanation about those well-known labels from [the docs](https://kubernetes.io/docs/reference/labels-annotations-taints/#app-kubernetes-io-instance) :

**app.kubernetes.io/instance** 
Type: Label

Example: app.kubernetes.io/instance: "mysql-abcxzy"

Used on: All Objects (typically used on [workload resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/)).

A unique name identifying the instance of an application. To assign a non-unique name, use [app.kubernetes.io/name](https://kubernetes.io/docs/reference/labels-annotations-taints/#app-kubernetes-io-name).

One of the [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels).

**app.kubernetes.io/managed-by**
Type: Label

Example: app.kubernetes.io/managed-by: "helm"

Used on: All Objects (typically used on [workload resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/)).

The tool being used to manage the operation of an application.

One of the [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels).

**app.kubernetes.io/name**
Type: Label

Example: app.kubernetes.io/name: "mysql"

Used on: All Objects (typically used on [workload resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/)).

The name of the application.

One of the [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels).

**app.kubernetes.io/part-of**
Type: Label

Example: app.kubernetes.io/part-of: "wordpress"

Used on: All Objects (typically used on [workload resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/)).

The name of a higher-level application this object is part of.

One of the [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels).

### Confusion

My confusion is in:

- `part-of` should be used for the name of the sum of all components, like in the example the "Wordpress" deployment.
- `name` is the name of the component, this should not be unique every time you deploy it. Like the name of a tool is what it is and therefore you know what is talked about.
- The particular `instance` of the component on the other hand should have a unique name.

### Humble question

Would you perhaps reconsider the usage of the well-known labels and include the `instance` label to make a deployment unique?
